#!/bin/bash

echo "🚀 User Registration System - Deployment Guide"
echo "=============================================="
echo ""

echo "📋 STEP 1: Deploy Backend to Railway"
echo "1. Go to https://railway.app and sign up/login"
echo "2. Click 'New Project' -> 'Deploy from GitHub repo'"
echo "3. Select your UserRegistration repository"
echo "4. Railway will auto-detect Node.js and use the root directory"
echo "5. Go to Variables tab and add these environment variables:"
echo "   - NODE_ENV=production"
echo "   - Any other variables from backend/.env.example"
echo "6. Your backend will be available at: https://your-project.railway.app"
echo ""

echo "📋 STEP 2: Deploy Frontend to Netlify"
echo "1. Go to https://netlify.com and sign up/login"
echo "2. Click 'Add new site' -> 'Import an existing project'"
echo "3. Connect to GitHub and select your repository"
echo "4. Configure build settings:"
echo "   - Base directory: (leave empty)"
echo "   - Build command: cd frontend && npm install && npm run build"
echo "   - Publish directory: frontend/build"
echo "5. Add environment variable:"
echo "   - Key: REACT_APP_API_URL"
echo "   - Value: https://your-project.railway.app (your Railway URL)"
echo "6. Deploy the site"
echo ""

echo "📋 STEP 3: Update CORS Settings"
echo "1. Note your Netlify URL (e.g., https://amazing-app-123.netlify.app)"
echo "2. Update backend/src/main.ts CORS settings with your Netlify URL"
echo "3. Push changes to GitHub (Railway will auto-redeploy)"
echo ""

echo "📋 STEP 4: Test Your Application"
echo "1. Visit your Netlify URL"
echo "2. Test user registration functionality"
echo "3. Check browser console for any errors"
echo ""

echo "🔧 Alternative: Deploy Backend to Render"
echo "1. Go to https://render.com and sign up/login"
echo "2. Click 'New' -> 'Web Service'"
echo "3. Connect GitHub repository"
echo "4. Configure:"
echo "   - Build Command: cd backend && npm install && npm run build"
echo "   - Start Command: cd backend && npm run start:prod"
echo "   - Add environment variables from backend/.env.example"
echo ""

echo "✅ Your deployment URLs will be:"
echo "- Frontend: https://your-app-name.netlify.app"
echo "- Backend: https://your-project.railway.app (or Render URL)"
echo ""
echo "Need help? Check the DEPLOYMENT.md file for detailed instructions!"